FROM osrf/ros:neotic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive

# 安装依赖，并配置ROS环境

RUN apt-get update && apt-get install -y \
    gedit x11-apps mesa-utils dbus-x11 \
    python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential \
    && echo "source /opt/ros/neotic/setup.bash" >> /root/.bashrc \
    && rosdep init || true \
    && rosdep update || true \
    && rm -rf /var/lib/apt/lists/*

# 工作目录
WORKDIR /root/catkin_ws

# 启动容器时默认执行的命令
CMD ["bash"]